controllers:
    resource:
        path: ../src/Infrastructure/Framework/Controller/
        namespace: App\Infrastructure\Framework\Controller
    type: attribute

book_routes:
    resource: ../src/Infrastructure/Framework/Controller/BookController.php
    type: attribute

author_routes:
    resource: ../src/Infrastructure/Framework/Controller/AuthorController.php
    type: attribute

borrow_routes:
    resource: ../src/Infrastructure/Framework/Controller/BorrowController.php
    type: attribute
